name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Executaos testes cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true

      # Upload Cypress test results as artifact
      - name: Upload Cypress test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results/*.json