name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
        continue-on-error: true  # Continue mesmo se os testes falharem

      # Create test file - Garantir que a etapa será executada, mesmo que o Cypress falhe
      - name: Create a test file
        if: always()  # Garante que essa etapa será executada independente do sucesso ou falha dos testes
        run: echo "Cypress Test Results" > cypress/results/test-results.txt

      # Upload Cypress test results as artifact - Garantir que seja feito mesmo em caso de falha
      - name: Upload test file
        if: always()  # Garante que será feito mesmo se houver falha no Cypress
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results/test-results.txt  # Ajuste o caminho se necessário

      # List files in results directory - Exibe os arquivos no diretório de resultados
      - name: List files in results directory
        if: always()  # Executa independentemente de falhas
        run: ls -la cypress/results/
