name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true

      # Step 1: Create a test file (test.txt)
      - name: Create a test file
        run: echo "Test file content" > test.txt

      # Step 2: Upload the test file as artifact
      - name: Upload test file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: test.txt

      # Step 3: List files in the results directory (optional debug)
      - name: List files in results directory
        run: ls -al cypress/results

      # Step 4: Upload Cypress test results as artifact
      - name: Upload Cypress test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results/*.json
