name: Cypress Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run cypress:run --browser ${{ matrix.browser }} --reporter mochawesome
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: cypress/reports
