name: Cypress Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print working directory
        run: pwd
      - name: Run Cypress tests
        run: npm run cypress:run