name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
        continue-on-error: true  # Continue mesmo se os testes falharem

      - name: Upload Cypress test results as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results/  # Aqui é onde os arquivos de resultado devem ser encontrados
      
      # List files in results directory - Exibe os arquivos no diretório de resultados
      - name: List files in results directory
        if: always()  # Executa independentemente de falhas
        run: ls -la cypress/results/
